# Generated by Django 2.2.6 on 2019-10-25 07:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Additional information stored as per requirements', null=True, verbose_name='Meta Information'),
        ),
    ]
