# Generated by Django 3.1.7 on 2021-02-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='meta',
            field=models.JSONField(blank=True, help_text='Additional information stored as per requirements', null=True, verbose_name='Meta Information'),
        ),
    ]
